AllCops:
  NewCops: enable
  SuggestExtensions: false

plugins:
  - rubocop-rails

Layout/AssignmentIndentation:
  Enabled: true

Layout/CommentIndentation:
  Enabled: true

Layout/EmptyLines:
  Enabled: true

Layout/EmptyLineBetweenDefs:
  Enabled: true

Layout/FirstHashElementIndentation:
  Enabled: true
  EnforcedStyle: consistent

Layout/IndentationConsistency:
  Enabled: true
  EnforcedStyle: normal

Layout/IndentationStyle:
  Enabled: true

Layout/IndentationWidth:
  Enabled: true
  Width: 2

Layout/RescueEnsureAlignment:
  Enabled: true

Layout/SpaceAroundBlockParameters:
  Enabled: true

Layout/SpaceBeforeBlockBraces:
  Enabled: true

Layout/SpaceInsideBlockBraces:
  Enabled: true

Layout/SpaceInsideHashLiteralBraces:
  Enabled: true

Layout/TrailingWhitespace:
  Enabled: true

Lint/RequireParentheses:
  Enabled: true

Naming/AsciiIdentifiers:
  Enabled: true

Naming/ClassAndModuleCamelCase:
  Enabled: true

Naming/FileName:
  Enabled: true

Naming/MethodName:
  Enabled: true

Naming/PredicatePrefix: # updated from PredicateName
  Enabled: true

Naming/VariableName:
  Enabled: true

Style/AndOr:
  Enabled: true

Style/BlockDelimiters:
  Enabled: true

Style/HashSyntax:
  Enabled: true
  EnforcedStyle: ruby19

Style/NumericLiterals:
  Enabled: true

# Optional: disable if you don't want to document every class/module
Style/Documentation:
  Enabled: false
